//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contactos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int IdContacto { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string E_Mail { get; set; }
        public string Morada { get; set; }
        public string Imagem { get; set; }
    }
}
